################################################################################
## ~/.config/chezmoi/.chezmoi.yaml
##
## Chezmoi configuration file in one of the supported formats (JSON, JSONC,
## TOML, and YAML).
## If multiple configuration file formats are present, chezmoi will report an
## error.
##
## Sources:
## - https://www.chezmoi.io/reference/configuration-file/
################################################################################

data:
    email: user.name@example.com
    hashedHostname: "965415361"
encryption: gpg
git:
    autoPush: true
sourceDir: /home/user/.dotfiles
