#cloud-config

# Tested on:
# - RHEL 8.6
# - Oracle Linux 8.6

# Upgrade the instance.
# Deactivated, as this could take a long time if the image is old.
#
# Sources:
# - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install
# - https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-apt-or-yum-upgrade
package_upgrade: false
package_reboot_if_required: false

# Install required packages.
# This will *always* update the list of packages, regardless of the value of the
# 'package_update' setting.
#
# Sources:
# - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install
# - https://cloudinit.readthedocs.io/en/latest/topics/examples.html#install-arbitrary-packages
packages:
  - jq
  - nc
  - traceroute
  - unzip
