version: '2'
services:
  client:
    image: boinc/client:arm32v7
    container_name: boinc-client
    restart: always
    network_mode: host
    pid: host
    volumes:
      - ./data:/var/lib/boinc
    environment:
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
      - BOINC_GUI_RPC_PASSWORD=123
      - BOINC_REMOTE_HOST=192.168.1.1
      - TZ=Europe/Dublin
